### PR TITLE
Issue #6 | Add SqlServer support | Adarsh

### PR DESCRIPTION
**Pull request by m4ver1k**

### CODE REVIEW

**Comment by m4ver1k** [comment]
@italolelis I see an error in coverall `flag needs an argument: -repotoken`.

**Comment by italolelis** [comment]
Hey @m4ver1k,

Thank you for  contribution. Regarding the failing CI, I think it has something to do with the way GithubActions work in a forked PR. The env var is set in this repo, but if the PR comes from a fork, it doesn't have access to that variable. I'll see if I can only run that step in master or something like that.

**Comment by italolelis** [comment]
@m4ver1k All right, now I have split the workflow for master and pull requests. I also updated our linting version, and now the PR has a few linting errors. If you don't mind fixing them I would appreciate it.

Thanks!!

**Comment by m4ver1k** [comment]
Sure will do that

**Comment by m4ver1k** [comment]
@italolelis I have fixed the linting issues.

**Comment by italolelis** [comment]
@m4ver1k Thank you very much for your contribution! 👍

**Pull request merged**
